# Generated by Django 3.2.8 on 2021-10-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nome',
        ),
        migrations.AddField(
            model_name='pedido',
            name='payment_intent',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_pago',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
