# Generated by Django 3.2.8 on 2021-10-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20211022_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='payment_intent',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
